export const WEATHER_API_KEY = '5e1fb1c9561f0bf70e6ba01348880258'
export const WEATHER_BASE_URL = 'https://api.openweathermap.org/data/2.5'
export const WEATHER_IMG_URL = 'https://openweathermap.org/img/w/'
export const WEATHER_TILE_URL = 'https://tile.openweathermap.org/map/'
export const WEATHER_TILE_FORMAT = '.png'